/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author wbo
 */
public class FrGeral extends javax.swing.JFrame {

    /**
     * Creates new form FrGeral
     */
    public FrGeral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundoGeral = new javax.swing.JPanel();
        lblImagemYatta = new javax.swing.JLabel();
        pnlFundoBotoes = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnPratas = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        pnlFundoGeral.setBackground(new java.awt.Color(255, 255, 255));

        lblImagemYatta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yatta (2).png"))); // NOI18N

        pnlFundoBotoes.setBackground(new java.awt.Color(255, 255, 255));

        btnCliente.setBackground(new java.awt.Color(231, 231, 231));
        btnCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Design sem nome (2).png"))); // NOI18N
        btnCliente.setText("CLIENTES");

        btnPratas.setBackground(new java.awt.Color(231, 231, 231));
        btnPratas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnPratas.setForeground(new java.awt.Color(0, 0, 0));
        btnPratas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Design sem nome (4).png"))); // NOI18N
        btnPratas.setText("PRATAS");
        btnPratas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPratasActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(231, 231, 231));
        btnPedidos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Design sem nome (6).png"))); // NOI18N
        btnPedidos.setText("PEDIDOS");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFundoBotoesLayout = new javax.swing.GroupLayout(pnlFundoBotoes);
        pnlFundoBotoes.setLayout(pnlFundoBotoesLayout);
        pnlFundoBotoesLayout.setHorizontalGroup(
            pnlFundoBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoBotoesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlFundoBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPratas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlFundoBotoesLayout.setVerticalGroup(
            pnlFundoBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoBotoesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCliente)
                .addGap(30, 30, 30)
                .addComponent(btnPratas)
                .addGap(28, 28, 28)
                .addComponent(btnPedidos)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFundoGeralLayout = new javax.swing.GroupLayout(pnlFundoGeral);
        pnlFundoGeral.setLayout(pnlFundoGeralLayout);
        pnlFundoGeralLayout.setHorizontalGroup(
            pnlFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagemYatta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFundoBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFundoGeralLayout.setVerticalGroup(
            pnlFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFundoBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagemYatta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFundoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPratasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPratasActionPerformed
       FrProduto tela = new FrProduto();
       tela.setVisible(true);
       tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPratasActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPratas;
    private javax.swing.JLabel lblImagemYatta;
    private javax.swing.JPanel pnlFundoBotoes;
    private javax.swing.JPanel pnlFundoGeral;
    // End of variables declaration//GEN-END:variables
}
