/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entities.Produto;
import gerenciadores.GerenciadorProdutos;
import javax.swing.JOptionPane;

/**
 *
 * @author wbo
 */
public class FrProduto extends javax.swing.JFrame {

    private int cod_Escolhido;
    private boolean editando;
    private GerenciadorProdutos gerente;

    public FrProduto() {
        initComponents();
        this.editando = false;
        this.habilitar_Campos(false);
        this.cod_Escolhido = 0;
        this.gerente = new GerenciadorProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        lblImagemLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCusto = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        lblEstoque = new javax.swing.JLabel();
        edtEstoque = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        edtCusto = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();
        bntNovo = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        bntDeletar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));

        lblImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yatta (2).png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblCusto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCusto.setForeground(new java.awt.Color(0, 0, 0));
        lblCusto.setText("Custo:");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(0, 0, 0));
        lblPreco.setText("Preço:");

        edtPreco.setBackground(new java.awt.Color(204, 204, 204));
        edtPreco.setForeground(new java.awt.Color(0, 0, 0));

        lblEstoque.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblEstoque.setForeground(new java.awt.Color(0, 0, 0));
        lblEstoque.setText("Estoque:");

        edtEstoque.setBackground(new java.awt.Color(204, 204, 204));
        edtEstoque.setForeground(new java.awt.Color(0, 0, 0));
        edtEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEstoqueActionPerformed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("ID:");

        edtCusto.setBackground(new java.awt.Color(204, 204, 204));
        edtCusto.setForeground(new java.awt.Color(0, 0, 0));

        edtNome.setBackground(new java.awt.Color(204, 204, 204));
        edtNome.setForeground(new java.awt.Color(0, 0, 0));

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome:");

        edtId.setBackground(new java.awt.Color(204, 204, 204));
        edtId.setForeground(new java.awt.Color(0, 0, 0));
        edtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstoque)
                    .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(edtPreco)
                    .addComponent(edtEstoque)
                    .addComponent(edtCusto)
                    .addComponent(edtId))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        edtListagem.setBackground(new java.awt.Color(204, 204, 204));
        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane2.setViewportView(edtListagem);

        bntNovo.setBackground(new java.awt.Color(255, 255, 255));
        bntNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo_32x32.png"))); // NOI18N
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });

        bntEditar.setBackground(new java.awt.Color(255, 255, 255));
        bntEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit3_32x32.png"))); // NOI18N
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntCancelar.setBackground(new java.awt.Color(255, 255, 255));
        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32x32.png"))); // NOI18N
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        bntDeletar.setBackground(new java.awt.Color(255, 255, 255));
        bntDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del_32x32.png"))); // NOI18N
        bntDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_32x32.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bntNovo)
                                .addGap(18, 18, 18)
                                .addComponent(bntEditar)
                                .addGap(18, 18, 18)
                                .addComponent(bntCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(bntDeletar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addGap(17, 17, 17)))))
                .addContainerGap())
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntDeletar)
                                    .addComponent(bntCancelar)
                                    .addComponent(btnSalvar))
                                .addGap(18, 18, 18))
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntNovo)
                                    .addComponent(bntEditar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEstoqueActionPerformed

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        limpar_Campos();
        habilitar_Campos(true);
        this.editando = false;
    }//GEN-LAST:event_bntNovoActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        String cod_Produto = JOptionPane.showInputDialog("Informe o codigo do produto:");
        this.cod_Escolhido = Integer.parseInt(cod_Produto);
        Produto produtoEditando = this.gerente.buscarProduto(cod_Escolhido);
        if (produtoEditando != null) {
            this.editando = true;
            this.limpar_Campos();
            this.habilitar_Campos(true);
            objetoParaCampos(produtoEditando);
        } else {
            JOptionPane.showMessageDialog(this, "Produto não localizado/cadastrado!");
        }

    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        limpar_Campos();
        habilitar_Campos(false);
        this.editando = false;
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (this.editando == true) {
            Produto novo_Produto = this.camposParaObjetoEditar();
            this.gerente.atualizarProduto(this.cod_Escolhido, novo_Produto);
        } else {
            Produto novoProduto = this.camposParaObjeto();
            gerente.addProduto(novoProduto);
        }
        limpar_Campos();
        habilitar_Campos(false);
        this.editando = false;
        String listagem = gerente.toString();
        edtListagem.setText(listagem);

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void bntDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletarActionPerformed
        String cod_produto = JOptionPane.showInputDialog("Informe o código do prodduto que deseja EXCLUIR:");
        this.cod_Escolhido = Integer.parseInt(cod_produto);
        Produto produto_excluir = this.gerente.buscarProduto(cod_Escolhido);
        if (produto_excluir != null) {
            gerente.remProduto(produto_excluir.getIdProduto());
            JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não localizado");
        }
        limpar_Campos();
        habilitar_Campos(false);
        String listagem = gerente.toString();
        edtListagem.setText(listagem);
    }//GEN-LAST:event_bntDeletarActionPerformed

    private void edtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public void limpar_Campos() {
        edtCusto.setText("");
        edtEstoque.setText("");
        edtNome.setText("");
        edtId.setText("");
        edtPreco.setText("");
    }

    public void objetoParaCampos(Produto produto) {
        edtNome.setText(produto.getNomeProduto());
        edtEstoque.setText(produto.getQtdProduto() + "");
        edtCusto.setText(produto.getPrecoProdutoCusto() + "");
        edtPreco.setText(produto.getPrecoProdutoVenda() + "");
        edtId.setText(produto.getIdProduto() + "");

    }

    public Produto camposParaObjetoEditar() {
        String nomep = edtNome.getText(); //Deve ser feito utilizando segundo construtor para não gerar NOVO ID
        double valueCost = Double.parseDouble(edtCusto.getText());
        double valuePrice = Double.parseDouble(edtPreco.getText());
        int valueStorage = Integer.parseInt(edtEstoque.getText());
        int idProduto = Integer.parseInt(edtId.getText());
        Produto produto = new Produto(nomep, valueStorage, valuePrice, valueCost, idProduto);
        return produto;
    }

    public Produto camposParaObjeto() {
        Produto produto = new Produto();
        produto.setNomeProduto(edtNome.getText());
        double value = Double.parseDouble(edtCusto.getText());
        produto.setPrecoProdutoCusto(value);
        value = Double.parseDouble(edtPreco.getText());
        produto.setPrecoProdutoVenda(value);
        int value2 = Integer.parseInt(edtEstoque.getText());
        produto.setQtdProduto(value2);
        return produto;
    }

    public void habilitar_Campos(boolean flag) {
        edtCusto.setEnabled(flag);
        edtEstoque.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtPreco.setEnabled(flag);
        edtId.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntDeletar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCusto;
    private javax.swing.JTextField edtEstoque;
    private javax.swing.JTextField edtId;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagemLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel pnlGeral;
    // End of variables declaration//GEN-END:variables
}
