/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;

import entities.Produto;
import gerenciadores.GerenciadorProdutos;
import javax.swing.JOptionPane;

/**
 *
 * @author wbo
 */
public class DlgCadProduto extends javax.swing.JDialog {

    private int cod_Escolhido;
    private boolean editando;
    private GerenciadorProdutos gerente;

    public DlgCadProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.editando = false;
        this.habilitar_Campos(false);
        this.cod_Escolhido = 0;
        this.gerente = new GerenciadorProdutos();
        gerente.carregarDoArquivo("ListagemProdutos.json");
        edtListagemProdutos.setText(gerente.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        btnNovoProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        btnCancelarProduto = new javax.swing.JButton();
        btnDeletarProduto = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblImagemLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagemProdutos = new javax.swing.JTextArea();
        lblId = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCusto = new javax.swing.JTextField();
        edtVenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));

        btnNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo_32x32.png"))); // NOI18N
        btnNovoProduto.setText("Novo Produto");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit3_32x32.png"))); // NOI18N
        btnEditarProduto.setText("Editar Produto");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        btnCancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32x32.png"))); // NOI18N
        btnCancelarProduto.setText("Cancelar Produto");
        btnCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutoActionPerformed(evt);
            }
        });

        btnDeletarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del_32x32.png"))); // NOI18N
        btnDeletarProduto.setText("Deletar Produto");
        btnDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarProdutoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar Produto");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yatta (2).png"))); // NOI18N

        edtListagemProdutos.setColumns(20);
        edtListagemProdutos.setRows(5);
        jScrollPane1.setViewportView(edtListagemProdutos);

        lblId.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId.setText("ID:");

        edtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIDActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNome.setText("Nome:");

        lblVenda.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblVenda.setText("Venda:");

        lblCusto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCusto.setText("Custo:");

        edtCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCustoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Estoque:");

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(btnNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarProduto)))
                        .addGap(30, 30, 30)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edtID, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(edtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtCusto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtVenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtEstoque, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCusto)
                            .addComponent(edtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVenda)
                            .addComponent(edtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoProduto)
                    .addComponent(btnCancelarProduto)
                    .addComponent(jLabel1)
                    .addComponent(edtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarProduto)
                    .addComponent(btnDeletarProduto)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        this.limpar_Campos();
        this.habilitar_Campos(true);
        this.editando = false;
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void edtCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCustoActionPerformed

    private void edtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIDActionPerformed

    private void btnCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutoActionPerformed
        this.limpar_Campos();
        this.habilitar_Campos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarProdutoActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        String cod_Produto = JOptionPane.showInputDialog("Informe o codigo do produto:");
        this.cod_Escolhido = Integer.parseInt(cod_Produto);
        Produto produtoEditando = this.gerente.buscarProduto(cod_Escolhido);
        if (produtoEditando != null) {
            this.editando = true;
            this.limpar_Campos();
            this.habilitar_Campos(true);
            objetoParaCampos(produtoEditando);
        } else {
            JOptionPane.showMessageDialog(this, "Produto não localizado/cadastrado!");
        }
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void btnDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarProdutoActionPerformed
        String cod_produto = JOptionPane.showInputDialog("Informe o código do prodduto que deseja EXCLUIR:");
        this.cod_Escolhido = Integer.parseInt(cod_produto);
        Produto produto_excluir = this.gerente.buscarProduto(cod_Escolhido);
        if (produto_excluir != null) {
            gerente.remProduto(produto_excluir.getIdProduto());
            JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não localizado");
        }
        limpar_Campos();
        habilitar_Campos(false);
        String listagem = gerente.toString();
        edtListagemProdutos.setText(listagem);
        gerente.salvarNoArquivo("ListagemProdutos.json");
    }//GEN-LAST:event_btnDeletarProdutoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (this.editando == true) {
            Produto novo_Produto = this.camposParaObjetoEditar();
            this.gerente.atualizarProduto(this.cod_Escolhido, novo_Produto);
        } else {
            Produto novoProduto = this.camposParaObjeto();
            gerente.addProduto(novoProduto);
        }
        limpar_Campos();
        habilitar_Campos(false);
        this.editando = false;
        String listagem = gerente.toString();
        edtListagemProdutos.setText(listagem);
       gerente.salvarNoArquivo("ListagemProdutos.json");
        
    }//GEN-LAST:event_btnSalvarActionPerformed

   public Produto camposParaObjeto() {
        Produto produto = new Produto();
        produto.setNomeProduto(edtNome.getText());
        double value = Double.parseDouble(edtCusto.getText());
        produto.setPrecoProdutoCusto(value);
        value = Double.parseDouble(edtVenda.getText());
        produto.setPrecoProdutoVenda(value);
        int value2 = Integer.parseInt(edtEstoque.getText());
        produto.setQtdProduto(value2);
        return produto;
    }

    public Produto camposParaObjetoEditar() {
        String nomep = edtNome.getText(); //Deve ser feito utilizando segundo construtor para não gerar NOVO ID
        double valueCost = Double.parseDouble(edtCusto.getText());
        double valuePrice = Double.parseDouble(edtVenda.getText());
        int valueStorage = Integer.parseInt(edtEstoque.getText());
        int idProduto = Integer.parseInt(edtID.getText());
        Produto produto = new Produto(nomep, valueStorage, valuePrice, valueCost, idProduto);
        return produto;
    }

     public void objetoParaCampos(Produto produto) {
        edtNome.setText(produto.getNomeProduto());
        edtEstoque.setText(produto.getQtdProduto() + "");
        edtCusto.setText(produto.getPrecoProdutoCusto() + "");
        edtVenda.setText(produto.getPrecoProdutoVenda() + "");
        edtID.setText(produto.getIdProduto() + "");

    }

    public void habilitar_Campos(boolean flag) {
        edtCusto.setEnabled(flag);
        edtID.setEnabled(false);
        edtNome.setEnabled(flag);
        edtVenda.setEnabled(flag);
    }

    public void limpar_Campos() {
        edtCusto.setText("");
        edtID.setText("");
        edtNome.setText("");
        edtVenda.setText("");
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProduto;
    private javax.swing.JButton btnDeletarProduto;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCusto;
    private javax.swing.JTextField edtEstoque;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextArea edtListagemProdutos;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagemLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JPanel pnlGeral;
    // End of variables declaration//GEN-END:variables
}
