/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;

import entities.Cliente;
import gerenciadores.GerenciadorCliente;
import javax.swing.JOptionPane;

/**
 *
 * @author wbo
 */
public class DlgCadCliente extends javax.swing.JDialog {

    private String cpf_Escolhido;
    private GerenciadorCliente gerente;
    private boolean editando;

    public DlgCadCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.editando = false;
        this.LimparCampos();
        this.HabilitarCampos(false);
        this.gerente = new GerenciadorCliente();
        gerente.carregarDoArquivo("ListagemClientes.json"); // ERRO ESTÁ NESSA LINHA
        edtListagemClientes.setText(gerente.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        btnNovoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();
        btnDeletarCliente = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblImagemLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagemClientes = new javax.swing.JTextArea();
        lblId = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCPF = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));

        btnNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo_32x32.png"))); // NOI18N
        btnNovoCliente.setText("Novo Cliente");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit3_32x32.png"))); // NOI18N
        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnCancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32x32.png"))); // NOI18N
        btnCancelarCliente.setText("Cancelar Cliente");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        btnDeletarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del_32x32.png"))); // NOI18N
        btnDeletarCliente.setText("Deletar Cliente");
        btnDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarClienteActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar Cliente");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yatta (2).png"))); // NOI18N

        edtListagemClientes.setColumns(20);
        edtListagemClientes.setRows(5);
        jScrollPane1.setViewportView(edtListagemClientes);

        lblId.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId.setText("ID:");

        edtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIDActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNome.setText("Nome:");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCPF.setText("CPF:");

        edtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarCliente))
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(pnlGeralLayout.createSequentialGroup()
                                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)))
                                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(edtID, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(edtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtTelefone, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF)
                            .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCliente)
                    .addComponent(btnCancelarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCliente)
                    .addComponent(btnDeletarCliente)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        this.LimparCampos();
        this.HabilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void edtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCPFActionPerformed

    private void edtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIDActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        this.LimparCampos();
        this.HabilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        cpf_Escolhido = JOptionPane.showInputDialog("Informe o CPF do cliente:");
        Cliente cliente_editando = this.gerente.find_cliente(cpf_Escolhido);
        if (cliente_editando != null) {
            this.editando = true;
            this.LimparCampos();
            this.HabilitarCampos(true);
            objetoParaCampos(cliente_editando);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente não localizado/cadastrado!");
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarClienteActionPerformed
        String cpf_cliente = JOptionPane.showInputDialog("Informe o CPF do cliente que deseja excluir:");
        Cliente cliente_excluir = this.gerente.find_cliente(cpf_cliente);
        if (cliente_excluir != null) {
            gerente.rem_cliente(cpf_cliente);
            JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
        } else
            JOptionPane.showMessageDialog(this, "Não localizado ou não existente no banco de dados");
        this.LimparCampos();
        this.HabilitarCampos(false);
        String listagem = gerente.toString();
        edtListagemClientes.setText(listagem);
        gerente.salvarNoArquivo("ListagemClientes.json");
    }//GEN-LAST:event_btnDeletarClienteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(this.editando == true){
            Cliente att_cliente = this.camposParaObjetoEditar();
            this.gerente.upt_cliente(cpf_Escolhido, att_cliente);
        }else{
            Cliente novo_cliente = this.camposParaObjeto();
            gerente.add_cliente(novo_cliente);
        }
        this.LimparCampos();
        this.HabilitarCampos(false);
        String listagem = gerente.toString();
        edtListagemClientes.setText(listagem);
        gerente.salvarNoArquivo("ListagemClientes.json");
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    public Cliente camposParaObjetoEditar() { //Utilizando segundo construtor para editar sem gerar um novo ID.
        String nome_cliente = edtNome.getText();
        String telefone_cliente = edtTelefone.getText();
        String cpf_cliente = edtCPF.getText();
        int id_cliente = Integer.parseInt(edtID.getText());
        Cliente cliente = new Cliente(nome_cliente, cpf_cliente, telefone_cliente, id_cliente);
        return cliente;
    }

    public Cliente camposParaObjeto() {
        Cliente cliente = new Cliente();
        cliente.setNome_cliente(edtNome.getText());
        cliente.setCpf_cliente(edtCPF.getText());
        cliente.setTelefone_cliente(edtTelefone.getText());
        return cliente;
    }

    public void objetoParaCampos(Cliente cliente) {
        edtNome.setText(cliente.getNome_cliente());
        edtCPF.setText(cliente.getCpf_cliente());
        edtTelefone.setText(cliente.getTelefone_cliente());
        edtID.setText(cliente.getId_cliente() + "");
    }

    public void HabilitarCampos(boolean flag) {
        edtCPF.setEnabled(flag);
        edtID.setEnabled(false);
        edtNome.setEnabled(flag);
        edtTelefone.setEnabled(flag);
    }

    public void LimparCampos() {
        edtCPF.setText("");
        edtID.setText("");
        edtNome.setText("");
        edtTelefone.setText("");
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnDeletarCliente;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextArea edtListagemClientes;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagemLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlGeral;
    // End of variables declaration//GEN-END:variables
}
