/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs.Pedido;

import gui.dialogs.*;
import entities.Cliente;
import entities.Pedido;
import entities.Produto;
import gerenciadores.GerenciadorCliente;
import gerenciadores.GerenciadorProdutos;
import javax.swing.JOptionPane;

/**
 *
 * @author wbo
 */
public class DlgEscolhaProduto extends javax.swing.JDialog {

    private Pedido pedido;
    public Produto produto_escolhido;
    private GerenciadorProdutos gerente_produto;

    public DlgEscolhaProduto(java.awt.Frame parent, boolean modal, Pedido pedido) {
        super(parent, modal);
        initComponents();
        this.produto_escolhido = new Produto();
        this.pedido = pedido;
        this.gerente_produto = new GerenciadorProdutos();
        this.gerente_produto.carregarDoArquivo("ListagemProdutos.csv");
        String listagem = this.gerente_produto.toString();
        edtListagemProdutos.setText(listagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        btnSalvarCliente = new javax.swing.JButton();
        lblImagemLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagemProdutos = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        btnBuscarProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtProdutoSelecionado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));

        btnSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_32x32.png"))); // NOI18N
        btnSalvarCliente.setText("Add Produto");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        lblImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yatta (2).png"))); // NOI18N

        edtListagemProdutos.setColumns(20);
        edtListagemProdutos.setRows(5);
        jScrollPane1.setViewportView(edtListagemProdutos);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCPF.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCPF.setText("ID:");

        btnBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        edtProdutoSelecionado.setColumns(20);
        edtProdutoSelecionado.setRows(5);
        edtProdutoSelecionado.setText("\n");
        edtProdutoSelecionado.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto Selecionado"));
        edtProdutoSelecionado.setCaretPosition(0);
        edtProdutoSelecionado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(edtProdutoSelecionado);
        edtProdutoSelecionado.getAccessibleContext().setAccessibleName("Produto Selecionado:");

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarProduto)
                            .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(lblImagemLogo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)))
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProduto)
                .addGap(10, 10, 10)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarCliente)
                            .addComponent(btnCancelar))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        if (produto_escolhido == null) {
            int response = JOptionPane.showConfirmDialog(null,
                    "Nenhum cliente foi escolhido. Deseja Continuar?",
                    "Confirm", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                dispose();
            }
        } else {
            this.pedido.addProduto(produto_escolhido);
            dispose();
        }

    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        int id_escolhido = Integer.parseInt(edtID.getText());
        produto_escolhido = this.gerente_produto.buscarProduto(id_escolhido);
        if (produto_escolhido == null) {
            JOptionPane.showMessageDialog(this, "Não há produto com este codigo no seu arquivo.");
            edtProdutoSelecionado.setText("");
        } else {
            edtProdutoSelecionado.setText(produto_escolhido.toString());
            if (produto_escolhido.getQtdProduto() >= 0) {
                produto_escolhido.setQtdProduto(produto_escolhido.getQtdProduto() - 1);
            } else {
                JOptionPane.showMessageDialog(this, "Você não possui mais estoque deste produto. Favor consultar estoque.");
            }
        }

    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        edtProdutoSelecionado.setText("");
        edtID.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextArea edtListagemProdutos;
    private javax.swing.JTextArea edtProdutoSelecionado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblImagemLogo;
    private javax.swing.JPanel pnlGeral;
    // End of variables declaration//GEN-END:variables
}
