/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs.Pedido;

import entities.Pedido;
import gui.dialogs.*;
import entities.Produto;
import gerenciadores.GerenciadorPedido;
import gerenciadores.GerenciadorProdutos;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author wbo
 */
public class DlgEdtPedido extends javax.swing.JDialog {

    private Pedido pedido_escolhido;
   
    private GerenciadorPedido gerente;

    public DlgEdtPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.habilitar_Campos(false);

        this.gerente = new GerenciadorPedido();
        gerente.carregarDoArquivo("ListagemPedidos.json");
        edtListagemPedidos.setText(gerente.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        lblImagemLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagemPedidos = new javax.swing.JTextArea();
        lblId = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        edtCliente = new javax.swing.JTextField();
        edtValor = new javax.swing.JTextField();
        btnBuscarPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtPedidoVisualizar = new javax.swing.JTextArea();
        btnEditarCliente = new javax.swing.JButton();
        btnAlterarItens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar Edição");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yatta (2).png"))); // NOI18N

        edtListagemPedidos.setColumns(20);
        edtListagemPedidos.setRows(5);
        edtListagemPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Pedidos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(edtListagemPedidos);

        lblId.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId.setText("ID:");

        edtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIDActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNome.setText("Cliente:");

        lblCusto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCusto.setText("Valor:");

        edtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtValorActionPerformed(evt);
            }
        });

        btnBuscarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPedidoActionPerformed(evt);
            }
        });

        edtPedidoVisualizar.setColumns(20);
        edtPedidoVisualizar.setRows(5);
        edtPedidoVisualizar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido Selecionado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        edtPedidoVisualizar.setName(""); // NOI18N
        jScrollPane2.setViewportView(edtPedidoVisualizar);

        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit3_32x32.png"))); // NOI18N
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnAlterarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit3_32x32.png"))); // NOI18N
        btnAlterarItens.setText("Alterar Itens");

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlGeralLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                            .addComponent(btnAlterarItens)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16)))
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edtID, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(edtCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtValor, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCusto)
                            .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarItens)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtValorActionPerformed

    private void edtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIDActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String listagem = gerente.toString();
        gerente.salvarNoArquivo("ListagemPedidos.json");
        edtListagemPedidos.setText(listagem);

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPedidoActionPerformed
        int id_pedido_editar = Integer.parseInt(edtID.getText());
        this.pedido_escolhido = this.gerente.find_pedido(id_pedido_editar);
        if (pedido_escolhido != null) {
            edtID.setText(pedido_escolhido.getId() + "");
            edtCliente.setText(pedido_escolhido.getCliente().getNome_cliente());
            edtValor.setText(pedido_escolhido.getValor_total() + "");
            edtPedidoVisualizar.setText(pedido_escolhido.toString());
        } else {
            JOptionPane.showMessageDialog(this, "Pedido não localizado.");
        }


    }//GEN-LAST:event_btnBuscarPedidoActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        DlgEscolhaCliente tela = new DlgEscolhaCliente(new JFrame(), true, this.pedido_escolhido);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        edtListagemPedidos.setText(gerente.toString());
        edtPedidoVisualizar.setText(this.pedido_escolhido.toString());
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    public void habilitar_Campos(boolean flag) {
        edtValor.setEnabled(flag);
        edtID.setEnabled(true);
        edtCliente.setEnabled(flag);

    }

    public void limpar_Campos() {
        edtValor.setText("");
        edtID.setText("");
        edtCliente.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarItens;
    private javax.swing.JButton btnBuscarPedido;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCliente;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextArea edtListagemPedidos;
    private javax.swing.JTextArea edtPedidoVisualizar;
    private javax.swing.JTextField edtValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagemLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlGeral;
    // End of variables declaration//GEN-END:variables
}
